namespace: new
replicaCount: 1
image:
  repository: sonuverma1505/hello-world-app
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: hello-world-app2
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30008
vault:
  role: hello-world-role
  secretPath: secret/clisecret
  serviceAccountName: vault-serviceaccount2
annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-secret-clisecret: "secret/hellovalue"
  vault.hashicorp.com/agent-inject-template-clisecret: |
    {{- with secret "secret/hellovalue" -}}
    {{ .Data.data.token }}
    {{- end }}
