namespace: new
replicaCount: 1
image:
  repository: sonuverma1505/hello-world-app
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: hello-world-app2
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30008
vault:
  serviceAccountName: vault-serviceaccount2
  secretFilePath: "/vault/secrets/hellovalue"
annotations:
  vault.hashicorp.com/role: "hello-world-role"
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-secret-hellovalue: "secret/hellovalue"
  vault.hashicorp.com/agent-inject-template-hellovalue: |
    {{- with secret "secret/hellovalue" -}}
    {{ .Data.data.token }}
    {{- end }}
