# Use the official Node.js image as the base image

FROM node:14



# Set the working directory inside the container

WORKDIR /usr/src/app



# Copy package.json and package-lock.json to the working directory

COPY package*.json ./



# Install the application dependencies

RUN npm install



# Copy the rest of the application code to the working directory

COPY . .



# Expose port 80 to the outside world

EXPOSE 80



# Define the command to run the application

CMD ["npm", "start"]