apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: {{ .Values.namespace }}
  labels:
    app: read-vault-secret
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: read-vault-secret
  template:
    metadata:
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
      labels:
        app: read-vault-secret
    spec:
      serviceAccountName: {{ .Values.vault.serviceAccountName }}
      containers:
      - name: hello-world-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}