apiVersion: v1
kind: Service
metadata:
  name: hello-world-app
  namespace: {{ .Values.namespace }}
  labels:
    app: read-vault-secret
spec:
  type: {{ .Values.service.type }}
  selector:
    app: read-vault-secret
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}