apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: app  # Use the 'app' namespace
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "hello-world-app"
    vault.hashicorp.com/agent-inject-secret-hello-world-secret: "secret/data/hello-world-app"
    vault.hashicorp.com/agent-inject-template-hello-world-secret: |
      {{- with secret "secret/data/hello-world-app" -}}
      {{ .Data.data.app-secret }}
      {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      serviceAccountName: default  # Ensure the correct service account with Vault permissions
      containers:
        - name: hello-world-app
          image: sonuverma1505/hello-world-app:latest  # Placeholder, update as necessary
          ports:
            - containerPort: 80
          env:
            - name: HELLO_WORLD_SECRET
              valueFrom:
                secretKeyRef:
                  name: hello-world-secret  # Kubernetes secret created by Vault Injector
                  key: hello-world-secret  # Key injected by Vault Agent
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-app
  namespace: app  # Use the 'app' namespace
spec:
  selector:
    app: hello-world-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
