apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-serviceaccount
  namespace: vault  # Use the 'vault' namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: vault
  labels:
    app: read-vault-secret
spec:
  selector:
    matchLabels:
      app: read-vault-secret
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-clisecret: "secret/clisecret"
        vault.hashicorp.com/agent-inject-template-clisecret: |
          {{- with secret "secret/clisecret" -}}
          {{ .Data.data.token }}
          {{- end }}
        vault.hashicorp.com/role: "vault-role"
      labels:
        app: read-vault-secret
    spec:
      serviceAccountName: vault-serviceaccount
      containers:
      - name: hello-world-app
        image: sonuverma1505/hello-world-app:latest # Placeholder, update as necessary
        ports:
        - containerPort: 80
        env:
        - name: SECRET_FILE_PATH
          value: "/vault/secrets/clisecret" # Path to the secret file
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-app
  namespace: vault
  labels:
    app: read-vault-secret
spec:
  type: NodePort
  selector:
    app: read-vault-secret
  ports:
  - protocol: TCP
    port: 80         # Service port
    targetPort: 80   # Container port
    nodePort: 30007  # NodePort
